services:
  frontend:
    image: kodemy-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${EXPOSE_PORT}:3000
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${API_URL}
      NEXT_PUBLIC_ERROR_HOLD_TIME_IN_MS: ${ERROR_HOLD_TIME_IN_MS}
    networks:
      - kodemy

networks:
  kodemy:
    driver: bridge

